version: 0.2

phases:
  pre_build:
    commands:
      - echo "Updating EC2 instance and installing dependencies..."
      - sudo yum update -y
      - sudo amazon-linux-extras enable docker
      - sudo yum install -y docker git
      - sudo service docker start
      - sudo usermod -aG docker ec2-user
      - echo "Dependencies installed successfully!"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-local-nginx .
      - echo "Docker image built successfully!"

  post_build:
    commands:
      - echo "Stopping any existing containers..."
      - docker stop my-nginx-container || true
      - docker rm my-nginx-container || true
      - echo "Running the new container..."
      - docker run -d -p 80:80 --name my-nginx-container my-local-nginx
      - echo "Deployment complete!"

artifacts:
  files:
    - buildspec.yml
